services:
  metatube:
    build:
      context: .
      dockerfile: Dockerfile
    image: metatube-go:latest
    container_name: metatube-go
    ports:
      - "8081:8080"
    restart: unless-stopped
    #depends_on:
    #  - postgres
    environment:
      - HTTP_PROXY=
      - HTTPS_PROXY=
    command: -no-db -port 8080

#  设置为无数据库模式时 不需要当前内容
#  postgres:
#    image: postgres:15-alpine
#    container_name: metatube-postgres
#    restart: unless-stopped
#    environment:
#      - POSTGRES_USER=metatube
#      - POSTGRES_PASSWORD=metatube
#      - POSTGRES_DB=metatube
#    volumes:
#      - ./db:/var/lib/postgresql/data
#      - run:/var/run
#    command: "-c TimeZone=Asia/Shanghai -c log_timezone=Asia/Shanghai -c listen_addresses='' -c unix_socket_permissions=0777"

volumes:
  run:
